#!/usr/bin/env bash

CACHE_DIR="$HOME/.cache/tmux-sessionizer"
mkdir -p $CACHE_DIR
  
if [[ $# -eq 1 ]]; then
	selected=$1
else
  COMMON_DIRS=$((
      find ~/Projects ~/Experiments -mindepth 1 -maxdepth 1 -type d
      cat ~/.cache/tmux-sessionizer/selected.log
    ) | sort | uniq -c | sort -nr | awk '{print $2}' )
	selected=$(echo "$COMMON_DIRS" | fzf)
fi

if [[ -z $selected ]]; then
	exit 0
fi

# Add cache entry - to increase the count of times it is accessed
echo $selected >>"$CACHE_DIR/selected.log"

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if ! tmux ls 2>/dev/null | grep -q -i "windows"; then
	tmux new-session -s $selected_name -c $selected
	exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
	tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
  tmux attach -t $selected_name
  exit 0
fi
tmux switch-client -t $selected_name
